USE TalentTrace;

insert into departments (deptID, companyID, deptName) values (1, '524', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (2, '265', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (3, '290', 'Design');
insert into departments (deptID, companyID, deptName) values (4, '253', 'IT');
insert into departments (deptID, companyID, deptName) values (5, '467', 'Sales');
insert into departments (deptID, companyID, deptName) values (6, '785', 'Marketing');
insert into departments (deptID, companyID, deptName) values (7, '269', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (8, '234', 'Design');
insert into departments (deptID, companyID, deptName) values (9, '100', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (10, '216', 'Sales');
insert into departments (deptID, companyID, deptName) values (11, '242', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (12, '452', 'Engineering');
insert into departments (deptID, companyID, deptName) values (13, '902', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (14, '116', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (15, '822', 'Operations');
insert into departments (deptID, companyID, deptName) values (16, '535', 'Finance');
insert into departments (deptID, companyID, deptName) values (17, '282', 'Design');
insert into departments (deptID, companyID, deptName) values (18, '492', 'Finance');
insert into departments (deptID, companyID, deptName) values (19, '662', 'Operations');
insert into departments (deptID, companyID, deptName) values (20, '336', 'IT');
insert into departments (deptID, companyID, deptName) values (21, '753', 'Operations');
insert into departments (deptID, companyID, deptName) values (22, '289', 'IT');
insert into departments (deptID, companyID, deptName) values (23, '917', 'Marketing');
insert into departments (deptID, companyID, deptName) values (24, '866', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (25, '448', 'Design');
insert into departments (deptID, companyID, deptName) values (26, '69', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (27, '91', 'Design');
insert into departments (deptID, companyID, deptName) values (28, '878', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (29, '880', 'IT');
insert into departments (deptID, companyID, deptName) values (30, '360', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (31, '837', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (32, '233', 'Marketing');
insert into departments (deptID, companyID, deptName) values (33, '138', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (34, '787', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (35, '799', 'Marketing');
insert into departments (deptID, companyID, deptName) values (36, '42', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (37, '57', 'Marketing');
insert into departments (deptID, companyID, deptName) values (38, '921', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (39, '483', 'IT');
insert into departments (deptID, companyID, deptName) values (40, '494', 'Operations');
insert into departments (deptID, companyID, deptName) values (41, '41', 'Design');
insert into departments (deptID, companyID, deptName) values (42, '143', 'Sales');
insert into departments (deptID, companyID, deptName) values (43, '61', 'IT');
insert into departments (deptID, companyID, deptName) values (44, '574', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (45, '658', 'Engineering');
insert into departments (deptID, companyID, deptName) values (46, '519', 'Operations');
insert into departments (deptID, companyID, deptName) values (47, '623', 'Operations');
insert into departments (deptID, companyID, deptName) values (48, '932', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (49, '820', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (50, '640', 'Finance');
insert into departments (deptID, companyID, deptName) values (51, '836', 'Operations');
insert into departments (deptID, companyID, deptName) values (52, '347', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (53, '5', 'Engineering');
insert into departments (deptID, companyID, deptName) values (54, '239', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (55, '875', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (56, '161', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (57, '825', 'Finance');
insert into departments (deptID, companyID, deptName) values (58, '459', 'Marketing');
insert into departments (deptID, companyID, deptName) values (59, '536', 'Engineering');
insert into departments (deptID, companyID, deptName) values (60, '855', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (61, '90', 'Marketing');
insert into departments (deptID, companyID, deptName) values (62, '219', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (63, '909', 'IT');
insert into departments (deptID, companyID, deptName) values (64, '566', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (65, '584', 'Operations');
insert into departments (deptID, companyID, deptName) values (66, '275', 'Engineering');
insert into departments (deptID, companyID, deptName) values (67, '283', 'Engineering');
insert into departments (deptID, companyID, deptName) values (68, '994', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (69, '133', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (70, '129', 'Operations');
insert into departments (deptID, companyID, deptName) values (71, '916', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (72, '819', 'Operations');
insert into departments (deptID, companyID, deptName) values (73, '455', 'Design');
insert into departments (deptID, companyID, deptName) values (74, '897', 'Sales');
insert into departments (deptID, companyID, deptName) values (75, '506', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (76, '666', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (77, '425', 'IT');
insert into departments (deptID, companyID, deptName) values (78, '268', 'Finance');
insert into departments (deptID, companyID, deptName) values (79, '576', 'Operations');
insert into departments (deptID, companyID, deptName) values (80, '604', 'Finance');
insert into departments (deptID, companyID, deptName) values (81, '630', 'Engineering');
insert into departments (deptID, companyID, deptName) values (82, '318', 'Finance');
insert into departments (deptID, companyID, deptName) values (83, '821', 'IT');
insert into departments (deptID, companyID, deptName) values (84, '929', 'IT');
insert into departments (deptID, companyID, deptName) values (85, '969', 'Marketing');
insert into departments (deptID, companyID, deptName) values (86, '622', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (87, '862', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (88, '562', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (89, '438', 'Operations');
insert into departments (deptID, companyID, deptName) values (90, '647', 'IT');
insert into departments (deptID, companyID, deptName) values (91, '613', 'Engineering');
insert into departments (deptID, companyID, deptName) values (92, '141', 'IT');
insert into departments (deptID, companyID, deptName) values (93, '513', 'Engineering');
insert into departments (deptID, companyID, deptName) values (94, '705', 'Operations');
insert into departments (deptID, companyID, deptName) values (95, '823', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (96, '818', 'Operations');
insert into departments (deptID, companyID, deptName) values (97, '193', 'Design');
insert into departments (deptID, companyID, deptName) values (98, '322', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (99, '988', 'Design');
insert into departments (deptID, companyID, deptName) values (100, '221', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (101, '941', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (102, '293', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (103, '458', 'Sales');
insert into departments (deptID, companyID, deptName) values (104, '641', 'Finance');
insert into departments (deptID, companyID, deptName) values (105, '199', 'Sales');
insert into departments (deptID, companyID, deptName) values (106, '636', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (107, '295', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (108, '957', 'Sales');
insert into departments (deptID, companyID, deptName) values (109, '873', 'Design');
insert into departments (deptID, companyID, deptName) values (110, '436', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (111, '543', 'IT');
insert into departments (deptID, companyID, deptName) values (112, '389', 'Operations');
insert into departments (deptID, companyID, deptName) values (113, '450', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (114, '245', 'Finance');
insert into departments (deptID, companyID, deptName) values (115, '373', 'IT');
insert into departments (deptID, companyID, deptName) values (116, '147', 'Design');
insert into departments (deptID, companyID, deptName) values (117, '207', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (118, '350', 'Engineering');
insert into departments (deptID, companyID, deptName) values (119, '471', 'Sales');
insert into departments (deptID, companyID, deptName) values (120, '943', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (121, '936', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (122, '401', 'Engineering');
insert into departments (deptID, companyID, deptName) values (123, '420', 'Finance');
insert into departments (deptID, companyID, deptName) values (124, '760', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (125, '126', 'Finance');
insert into departments (deptID, companyID, deptName) values (126, '2', 'Finance');
insert into departments (deptID, companyID, deptName) values (127, '556', 'Operations');
insert into departments (deptID, companyID, deptName) values (128, '225', 'Marketing');
insert into departments (deptID, companyID, deptName) values (129, '985', 'Sales');
insert into departments (deptID, companyID, deptName) values (130, '775', 'IT');
insert into departments (deptID, companyID, deptName) values (131, '529', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (132, '750', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (133, '426', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (134, '648', 'Sales');
insert into departments (deptID, companyID, deptName) values (135, '200', 'Finance');
insert into departments (deptID, companyID, deptName) values (136, '115', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (137, '378', 'Operations');
insert into departments (deptID, companyID, deptName) values (138, '727', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (139, '128', 'Engineering');
insert into departments (deptID, companyID, deptName) values (140, '639', 'Engineering');
insert into departments (deptID, companyID, deptName) values (141, '901', 'Sales');
insert into departments (deptID, companyID, deptName) values (142, '728', 'Sales');
insert into departments (deptID, companyID, deptName) values (143, '156', 'Sales');
insert into departments (deptID, companyID, deptName) values (144, '342', 'Operations');
insert into departments (deptID, companyID, deptName) values (145, '933', 'Finance');
insert into departments (deptID, companyID, deptName) values (146, '190', 'Marketing');
insert into departments (deptID, companyID, deptName) values (147, '979', 'Operations');
insert into departments (deptID, companyID, deptName) values (148, '353', 'Operations');
insert into departments (deptID, companyID, deptName) values (149, '162', 'Finance');
insert into departments (deptID, companyID, deptName) values (150, '364', 'Sales');
insert into departments (deptID, companyID, deptName) values (151, '415', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (152, '79', 'Operations');
insert into departments (deptID, companyID, deptName) values (153, '49', 'Sales');
insert into departments (deptID, companyID, deptName) values (154, '464', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (155, '160', 'Operations');
insert into departments (deptID, companyID, deptName) values (156, '377', 'Finance');
insert into departments (deptID, companyID, deptName) values (157, '331', 'Operations');
insert into departments (deptID, companyID, deptName) values (158, '329', 'Engineering');
insert into departments (deptID, companyID, deptName) values (159, '469', 'Operations');
insert into departments (deptID, companyID, deptName) values (160, '454', 'Sales');
insert into departments (deptID, companyID, deptName) values (161, '968', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (162, '185', 'IT');
insert into departments (deptID, companyID, deptName) values (163, '62', 'IT');
insert into departments (deptID, companyID, deptName) values (164, '375', 'Marketing');
insert into departments (deptID, companyID, deptName) values (165, '419', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (166, '579', 'Design');
insert into departments (deptID, companyID, deptName) values (167, '332', 'Engineering');
insert into departments (deptID, companyID, deptName) values (168, '121', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (169, '386', 'Finance');
insert into departments (deptID, companyID, deptName) values (170, '433', 'Marketing');
insert into departments (deptID, companyID, deptName) values (171, '954', 'Sales');
insert into departments (deptID, companyID, deptName) values (172, '493', 'Engineering');
insert into departments (deptID, companyID, deptName) values (173, '779', 'IT');
insert into departments (deptID, companyID, deptName) values (174, '801', 'Finance');
insert into departments (deptID, companyID, deptName) values (175, '633', 'Operations');
insert into departments (deptID, companyID, deptName) values (176, '734', 'Marketing');
insert into departments (deptID, companyID, deptName) values (177, '157', 'Engineering');
insert into departments (deptID, companyID, deptName) values (178, '946', 'Operations');
insert into departments (deptID, companyID, deptName) values (179, '272', 'Finance');
insert into departments (deptID, companyID, deptName) values (180, '504', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (181, '776', 'Design');
insert into departments (deptID, companyID, deptName) values (182, '73', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (183, '912', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (184, '72', 'Sales');
insert into departments (deptID, companyID, deptName) values (185, '685', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (186, '958', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (187, '798', 'Engineering');
insert into departments (deptID, companyID, deptName) values (188, '472', 'Engineering');
insert into departments (deptID, companyID, deptName) values (189, '19', 'Marketing');
insert into departments (deptID, companyID, deptName) values (190, '431', 'Finance');
insert into departments (deptID, companyID, deptName) values (191, '911', 'Finance');
insert into departments (deptID, companyID, deptName) values (192, '950', 'Design');
insert into departments (deptID, companyID, deptName) values (193, '101', 'Operations');
insert into departments (deptID, companyID, deptName) values (194, '571', 'Finance');
insert into departments (deptID, companyID, deptName) values (195, '528', 'Sales');
insert into departments (deptID, companyID, deptName) values (196, '491', 'Design');
insert into departments (deptID, companyID, deptName) values (197, '794', 'Finance');
insert into departments (deptID, companyID, deptName) values (198, '306', 'Finance');
insert into departments (deptID, companyID, deptName) values (199, '826', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (200, '16', 'IT');
insert into departments (deptID, companyID, deptName) values (201, '754', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (202, '370', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (203, '372', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (204, '953', 'IT');
insert into departments (deptID, companyID, deptName) values (205, '993', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (206, '920', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (207, '130', 'Finance');
insert into departments (deptID, companyID, deptName) values (208, '894', 'Design');
insert into departments (deptID, companyID, deptName) values (209, '158', 'Operations');
insert into departments (deptID, companyID, deptName) values (210, '514', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (211, '967', 'Design');
insert into departments (deptID, companyID, deptName) values (212, '34', 'Marketing');
insert into departments (deptID, companyID, deptName) values (213, '320', 'IT');
insert into departments (deptID, companyID, deptName) values (214, '477', 'Sales');
insert into departments (deptID, companyID, deptName) values (215, '407', 'Finance');
insert into departments (deptID, companyID, deptName) values (216, '784', 'Design');
insert into departments (deptID, companyID, deptName) values (217, '137', 'Sales');
insert into departments (deptID, companyID, deptName) values (218, '363', 'Sales');
insert into departments (deptID, companyID, deptName) values (219, '136', 'Design');
insert into departments (deptID, companyID, deptName) values (220, '888', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (221, '720', 'Sales');
insert into departments (deptID, companyID, deptName) values (222, '816', 'Operations');
insert into departments (deptID, companyID, deptName) values (223, '738', 'Marketing');
insert into departments (deptID, companyID, deptName) values (224, '421', 'Engineering');
insert into departments (deptID, companyID, deptName) values (225, '545', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (226, '168', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (227, '327', 'Engineering');
insert into departments (deptID, companyID, deptName) values (228, '863', 'Design');
insert into departments (deptID, companyID, deptName) values (229, '312', 'Operations');
insert into departments (deptID, companyID, deptName) values (230, '650', 'Design');
insert into departments (deptID, companyID, deptName) values (231, '531', 'Marketing');
insert into departments (deptID, companyID, deptName) values (232, '428', 'Design');
insert into departments (deptID, companyID, deptName) values (233, '277', 'Finance');
insert into departments (deptID, companyID, deptName) values (234, '482', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (235, '475', 'IT');
insert into departments (deptID, companyID, deptName) values (236, '145', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (237, '510', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (238, '488', 'Design');
insert into departments (deptID, companyID, deptName) values (239, '599', 'IT');
insert into departments (deptID, companyID, deptName) values (240, '796', 'Operations');
insert into departments (deptID, companyID, deptName) values (241, '15', 'Design');
insert into departments (deptID, companyID, deptName) values (242, '30', 'IT');
insert into departments (deptID, companyID, deptName) values (243, '644', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (244, '47', 'IT');
insert into departments (deptID, companyID, deptName) values (245, '273', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (246, '449', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (247, '689', 'Finance');
insert into departments (deptID, companyID, deptName) values (248, '834', 'Design');
insert into departments (deptID, companyID, deptName) values (249, '711', 'Finance');
insert into departments (deptID, companyID, deptName) values (250, '352', 'Sales');
insert into departments (deptID, companyID, deptName) values (251, '480', 'Operations');
insert into departments (deptID, companyID, deptName) values (252, '112', 'IT');
insert into departments (deptID, companyID, deptName) values (253, '302', 'IT');
insert into departments (deptID, companyID, deptName) values (254, '13', 'Sales');
insert into departments (deptID, companyID, deptName) values (255, '317', 'Sales');
insert into departments (deptID, companyID, deptName) values (256, '440', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (257, '547', 'Sales');
insert into departments (deptID, companyID, deptName) values (258, '577', 'Sales');
insert into departments (deptID, companyID, deptName) values (259, '563', 'Engineering');
insert into departments (deptID, companyID, deptName) values (260, '814', 'Sales');
insert into departments (deptID, companyID, deptName) values (261, '809', 'Marketing');
insert into departments (deptID, companyID, deptName) values (262, '230', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (263, '559', 'Marketing');
insert into departments (deptID, companyID, deptName) values (264, '294', 'Operations');
insert into departments (deptID, companyID, deptName) values (265, '668', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (266, '872', 'Marketing');
insert into departments (deptID, companyID, deptName) values (267, '757', 'Operations');
insert into departments (deptID, companyID, deptName) values (268, '686', 'Finance');
insert into departments (deptID, companyID, deptName) values (269, '191', 'IT');
insert into departments (deptID, companyID, deptName) values (270, '325', 'Engineering');
insert into departments (deptID, companyID, deptName) values (271, '512', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (272, '808', 'Engineering');
insert into departments (deptID, companyID, deptName) values (273, '539', 'Operations');
insert into departments (deptID, companyID, deptName) values (274, '171', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (275, '357', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (276, '643', 'Finance');
insert into departments (deptID, companyID, deptName) values (277, '805', 'Finance');
insert into departments (deptID, companyID, deptName) values (278, '924', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (279, '595', 'Finance');
insert into departments (deptID, companyID, deptName) values (280, '181', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (281, '844', 'IT');
insert into departments (deptID, companyID, deptName) values (282, '321', 'Design');
insert into departments (deptID, companyID, deptName) values (283, '11', 'Marketing');
insert into departments (deptID, companyID, deptName) values (284, '263', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (285, '264', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (286, '582', 'Operations');
insert into departments (deptID, companyID, deptName) values (287, '466', 'Design');
insert into departments (deptID, companyID, deptName) values (288, '810', 'Design');
insert into departments (deptID, companyID, deptName) values (289, '674', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (290, '860', 'Engineering');
insert into departments (deptID, companyID, deptName) values (291, '507', 'IT');
insert into departments (deptID, companyID, deptName) values (292, '164', 'Marketing');
insert into departments (deptID, companyID, deptName) values (293, '337', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (294, '712', 'Engineering');
insert into departments (deptID, companyID, deptName) values (295, '159', 'Operations');
insert into departments (deptID, companyID, deptName) values (296, '777', 'Finance');
insert into departments (deptID, companyID, deptName) values (297, '575', 'Design');
insert into departments (deptID, companyID, deptName) values (298, '704', 'Design');
insert into departments (deptID, companyID, deptName) values (299, '850', 'Marketing');
insert into departments (deptID, companyID, deptName) values (300, '496', 'Marketing');
insert into departments (deptID, companyID, deptName) values (301, '502', 'Sales');
insert into departments (deptID, companyID, deptName) values (302, '418', 'Design');
insert into departments (deptID, companyID, deptName) values (303, '362', 'IT');
insert into departments (deptID, companyID, deptName) values (304, '701', 'Engineering');
insert into departments (deptID, companyID, deptName) values (305, '32', 'Finance');
insert into departments (deptID, companyID, deptName) values (306, '106', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (307, '966', 'Engineering');
insert into departments (deptID, companyID, deptName) values (308, '339', 'Finance');
insert into departments (deptID, companyID, deptName) values (309, '59', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (310, '748', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (311, '807', 'Finance');
insert into departments (deptID, companyID, deptName) values (312, '868', 'Engineering');
insert into departments (deptID, companyID, deptName) values (313, '223', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (314, '716', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (315, '549', 'Operations');
insert into departments (deptID, companyID, deptName) values (316, '847', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (317, '204', 'Finance');
insert into departments (deptID, companyID, deptName) values (318, '621', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (319, '228', 'Sales');
insert into departments (deptID, companyID, deptName) values (320, '442', 'Sales');
insert into departments (deptID, companyID, deptName) values (321, '247', 'Finance');
insert into departments (deptID, companyID, deptName) values (322, '355', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (323, '664', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (324, '992', 'Marketing');
insert into departments (deptID, companyID, deptName) values (325, '99', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (326, '713', 'IT');
insert into departments (deptID, companyID, deptName) values (327, '38', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (328, '939', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (329, '381', 'IT');
insert into departments (deptID, companyID, deptName) values (330, '915', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (331, '698', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (332, '557', 'Finance');
insert into departments (deptID, companyID, deptName) values (333, '490', 'Marketing');
insert into departments (deptID, companyID, deptName) values (334, '403', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (335, '470', 'Operations');
insert into departments (deptID, companyID, deptName) values (336, '755', 'IT');
insert into departments (deptID, companyID, deptName) values (337, '678', 'Operations');
insert into departments (deptID, companyID, deptName) values (338, '555', 'Sales');
insert into departments (deptID, companyID, deptName) values (339, '148', 'Operations');
insert into departments (deptID, companyID, deptName) values (340, '244', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (341, '790', 'Finance');
insert into departments (deptID, companyID, deptName) values (342, '990', 'Engineering');
insert into departments (deptID, companyID, deptName) values (343, '561', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (344, '226', 'Engineering');
insert into departments (deptID, companyID, deptName) values (345, '730', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (346, '997', 'Design');
insert into departments (deptID, companyID, deptName) values (347, '749', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (348, '9', 'Sales');
insert into departments (deptID, companyID, deptName) values (349, '634', 'Sales');
insert into departments (deptID, companyID, deptName) values (350, '540', 'Sales');
insert into departments (deptID, companyID, deptName) values (351, '544', 'Marketing');
insert into departments (deptID, companyID, deptName) values (352, '766', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (353, '829', 'IT');
insert into departments (deptID, companyID, deptName) values (354, '23', 'Finance');
insert into departments (deptID, companyID, deptName) values (355, '443', 'Operations');
insert into departments (deptID, companyID, deptName) values (356, '688', 'Engineering');
insert into departments (deptID, companyID, deptName) values (357, '792', 'Engineering');
insert into departments (deptID, companyID, deptName) values (358, '707', 'Sales');
insert into departments (deptID, companyID, deptName) values (359, '96', 'IT');
insert into departments (deptID, companyID, deptName) values (360, '803', 'Sales');
insert into departments (deptID, companyID, deptName) values (361, '735', 'Marketing');
insert into departments (deptID, companyID, deptName) values (362, '942', 'Marketing');
insert into departments (deptID, companyID, deptName) values (363, '94', 'Finance');
insert into departments (deptID, companyID, deptName) values (364, '786', 'IT');
insert into departments (deptID, companyID, deptName) values (365, '304', 'Finance');
insert into departments (deptID, companyID, deptName) values (366, '817', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (367, '715', 'IT');
insert into departments (deptID, companyID, deptName) values (368, '174', 'Design');
insert into departments (deptID, companyID, deptName) values (369, '546', 'Operations');
insert into departments (deptID, companyID, deptName) values (370, '927', 'IT');
insert into departments (deptID, companyID, deptName) values (371, '365', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (372, '521', 'Operations');
insert into departments (deptID, companyID, deptName) values (373, '287', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (374, '344', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (375, '838', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (376, '651', 'Sales');
insert into departments (deptID, companyID, deptName) values (377, '537', 'IT');
insert into departments (deptID, companyID, deptName) values (378, '414', 'Operations');
insert into departments (deptID, companyID, deptName) values (379, '474', 'IT');
insert into departments (deptID, companyID, deptName) values (380, '797', 'Sales');
insert into departments (deptID, companyID, deptName) values (381, '392', 'Marketing');
insert into departments (deptID, companyID, deptName) values (382, '111', 'Marketing');
insert into departments (deptID, companyID, deptName) values (383, '726', 'Finance');
insert into departments (deptID, companyID, deptName) values (384, '778', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (385, '661', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (386, '657', 'Operations');
insert into departments (deptID, companyID, deptName) values (387, '349', 'Operations');
insert into departments (deptID, companyID, deptName) values (388, '87', 'Design');
insert into departments (deptID, companyID, deptName) values (389, '765', 'Design');
insert into departments (deptID, companyID, deptName) values (390, '117', 'Finance');
insert into departments (deptID, companyID, deptName) values (391, '617', 'Design');
insert into departments (deptID, companyID, deptName) values (392, '399', 'Finance');
insert into departments (deptID, companyID, deptName) values (393, '568', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (394, '298', 'IT');
insert into departments (deptID, companyID, deptName) values (395, '899', 'IT');
insert into departments (deptID, companyID, deptName) values (396, '372', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (397, '926', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (398, '131', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (399, '886', 'Marketing');
insert into departments (deptID, companyID, deptName) values (400, '15', 'Engineering');
insert into departments (deptID, companyID, deptName) values (401, '35', 'Engineering');
insert into departments (deptID, companyID, deptName) values (402, '257', 'IT');
insert into departments (deptID, companyID, deptName) values (403, '681', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (404, '891', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (405, '679', 'Marketing');
insert into departments (deptID, companyID, deptName) values (406, '196', 'Operations');
insert into departments (deptID, companyID, deptName) values (407, '145', 'Engineering');
insert into departments (deptID, companyID, deptName) values (408, '641', 'IT');
insert into departments (deptID, companyID, deptName) values (409, '103', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (410, '454', 'Engineering');
insert into departments (deptID, companyID, deptName) values (411, '967', 'Sales');
insert into departments (deptID, companyID, deptName) values (412, '121', 'IT');
insert into departments (deptID, companyID, deptName) values (413, '459', 'IT');
insert into departments (deptID, companyID, deptName) values (414, '876', 'Finance');
insert into departments (deptID, companyID, deptName) values (415, '207', 'Sales');
insert into departments (deptID, companyID, deptName) values (416, '927', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (417, '515', 'IT');
insert into departments (deptID, companyID, deptName) values (418, '101', 'IT');
insert into departments (deptID, companyID, deptName) values (419, '932', 'Engineering');
insert into departments (deptID, companyID, deptName) values (420, '367', 'Engineering');
insert into departments (deptID, companyID, deptName) values (421, '503', 'Operations');
insert into departments (deptID, companyID, deptName) values (422, '384', 'Finance');
insert into departments (deptID, companyID, deptName) values (423, '612', 'IT');
insert into departments (deptID, companyID, deptName) values (424, '974', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (425, '855', 'Design');
insert into departments (deptID, companyID, deptName) values (426, '940', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (427, '880', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (428, '437', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (429, '427', 'Design');
insert into departments (deptID, companyID, deptName) values (430, '245', 'Sales');
insert into departments (deptID, companyID, deptName) values (431, '740', 'Finance');
insert into departments (deptID, companyID, deptName) values (432, '792', 'IT');
insert into departments (deptID, companyID, deptName) values (433, '584', 'Finance');
insert into departments (deptID, companyID, deptName) values (434, '467', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (435, '817', 'IT');
insert into departments (deptID, companyID, deptName) values (436, '633', 'Engineering');
insert into departments (deptID, companyID, deptName) values (437, '431', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (438, '893', 'Design');
insert into departments (deptID, companyID, deptName) values (439, '283', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (440, '815', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (441, '143', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (442, '448', 'IT');
insert into departments (deptID, companyID, deptName) values (443, '146', 'Sales');
insert into departments (deptID, companyID, deptName) values (444, '228', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (445, '149', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (446, '712', 'Finance');
insert into departments (deptID, companyID, deptName) values (447, '472', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (448, '185', 'Sales');
insert into departments (deptID, companyID, deptName) values (449, '713', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (450, '224', 'Finance');
insert into departments (deptID, companyID, deptName) values (451, '291', 'Marketing');
insert into departments (deptID, companyID, deptName) values (452, '704', 'Design');
insert into departments (deptID, companyID, deptName) values (453, '182', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (454, '729', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (455, '237', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (456, '457', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (457, '767', 'Design');
insert into departments (deptID, companyID, deptName) values (458, '305', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (459, '408', 'Operations');
insert into departments (deptID, companyID, deptName) values (460, '586', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (461, '23', 'Operations');
insert into departments (deptID, companyID, deptName) values (462, '39', 'Design');
insert into departments (deptID, companyID, deptName) values (463, '328', 'Marketing');
insert into departments (deptID, companyID, deptName) values (464, '955', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (465, '154', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (466, '93', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (467, '29', 'Design');
insert into departments (deptID, companyID, deptName) values (468, '159', 'Marketing');
insert into departments (deptID, companyID, deptName) values (469, '961', 'Finance');
insert into departments (deptID, companyID, deptName) values (470, '274', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (471, '988', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (472, '714', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (473, '741', 'Sales');
insert into departments (deptID, companyID, deptName) values (474, '423', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (475, '843', 'Sales');
insert into departments (deptID, companyID, deptName) values (476, '982', 'Marketing');
insert into departments (deptID, companyID, deptName) values (477, '994', 'Finance');
insert into departments (deptID, companyID, deptName) values (478, '517', 'Engineering');
insert into departments (deptID, companyID, deptName) values (479, '858', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (480, '784', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (481, '438', 'Marketing');
insert into departments (deptID, companyID, deptName) values (482, '538', 'Finance');
insert into departments (deptID, companyID, deptName) values (483, '701', 'Engineering');
insert into departments (deptID, companyID, deptName) values (484, '804', 'Sales');
insert into departments (deptID, companyID, deptName) values (485, '393', 'Finance');
insert into departments (deptID, companyID, deptName) values (486, '195', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (487, '772', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (488, '761', 'Finance');
insert into departments (deptID, companyID, deptName) values (489, '860', 'Operations');
insert into departments (deptID, companyID, deptName) values (490, '716', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (491, '825', 'IT');
insert into departments (deptID, companyID, deptName) values (492, '266', 'Finance');
insert into departments (deptID, companyID, deptName) values (493, '499', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (494, '619', 'Sales');
insert into departments (deptID, companyID, deptName) values (495, '530', 'Design');
insert into departments (deptID, companyID, deptName) values (496, '877', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (497, '36', 'Design');
insert into departments (deptID, companyID, deptName) values (498, '102', 'IT');
insert into departments (deptID, companyID, deptName) values (499, '696', 'Engineering');
insert into departments (deptID, companyID, deptName) values (500, '690', 'Finance');
insert into departments (deptID, companyID, deptName) values (501, '100', 'IT');
insert into departments (deptID, companyID, deptName) values (502, '1000', 'Finance');
insert into departments (deptID, companyID, deptName) values (503, '991', 'Marketing');
insert into departments (deptID, companyID, deptName) values (504, '587', 'Finance');
insert into departments (deptID, companyID, deptName) values (505, '338', 'Engineering');
insert into departments (deptID, companyID, deptName) values (506, '752', 'IT');
insert into departments (deptID, companyID, deptName) values (507, '966', 'Finance');
insert into departments (deptID, companyID, deptName) values (508, '593', 'Design');
insert into departments (deptID, companyID, deptName) values (509, '791', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (510, '127', 'IT');
insert into departments (deptID, companyID, deptName) values (511, '355', 'Sales');
insert into departments (deptID, companyID, deptName) values (512, '171', 'Operations');
insert into departments (deptID, companyID, deptName) values (513, '261', 'Marketing');
insert into departments (deptID, companyID, deptName) values (514, '98', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (515, '630', 'IT');
insert into departments (deptID, companyID, deptName) values (516, '390', 'Marketing');
insert into departments (deptID, companyID, deptName) values (517, '430', 'Finance');
insert into departments (deptID, companyID, deptName) values (518, '614', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (519, '548', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (520, '164', 'Operations');
insert into departments (deptID, companyID, deptName) values (521, '192', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (522, '859', 'Operations');
insert into departments (deptID, companyID, deptName) values (523, '519', 'Operations');
insert into departments (deptID, companyID, deptName) values (524, '958', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (525, '236', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (526, '118', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (527, '578', 'Operations');
insert into departments (deptID, companyID, deptName) values (528, '426', 'IT');
insert into departments (deptID, companyID, deptName) values (529, '598', 'Engineering');
insert into departments (deptID, companyID, deptName) values (530, '688', 'Marketing');
insert into departments (deptID, companyID, deptName) values (531, '812', 'Marketing');
insert into departments (deptID, companyID, deptName) values (532, '439', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (533, '902', 'Sales');
insert into departments (deptID, companyID, deptName) values (534, '54', 'Finance');
insert into departments (deptID, companyID, deptName) values (535, '511', 'Operations');
insert into departments (deptID, companyID, deptName) values (536, '790', 'Design');
insert into departments (deptID, companyID, deptName) values (537, '160', 'Finance');
insert into departments (deptID, companyID, deptName) values (538, '294', 'Sales');
insert into departments (deptID, companyID, deptName) values (539, '480', 'Finance');
insert into departments (deptID, companyID, deptName) values (540, '362', 'Marketing');
insert into departments (deptID, companyID, deptName) values (541, '609', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (542, '828', 'Sales');
insert into departments (deptID, companyID, deptName) values (543, '571', 'Engineering');
insert into departments (deptID, companyID, deptName) values (544, '867', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (545, '263', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (546, '232', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (547, '785', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (548, '948', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (549, '299', 'Operations');
insert into departments (deptID, companyID, deptName) values (550, '872', 'Operations');
insert into departments (deptID, companyID, deptName) values (551, '819', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (552, '243', 'Marketing');
insert into departments (deptID, companyID, deptName) values (553, '623', 'Engineering');
insert into departments (deptID, companyID, deptName) values (554, '959', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (555, '63', 'Operations');
insert into departments (deptID, companyID, deptName) values (556, '449', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (557, '20', 'Operations');
insert into departments (deptID, companyID, deptName) values (558, '26', 'Sales');
insert into departments (deptID, companyID, deptName) values (559, '528', 'Operations');
insert into departments (deptID, companyID, deptName) values (560, '938', 'IT');
insert into departments (deptID, companyID, deptName) values (561, '410', 'Marketing');
insert into departments (deptID, companyID, deptName) values (562, '41', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (563, '246', 'Sales');
insert into departments (deptID, companyID, deptName) values (564, '352', 'Marketing');
insert into departments (deptID, companyID, deptName) values (565, '475', 'Finance');
insert into departments (deptID, companyID, deptName) values (566, '537', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (567, '157', 'Sales');
insert into departments (deptID, companyID, deptName) values (568, '191', 'Engineering');
insert into departments (deptID, companyID, deptName) values (569, '234', 'Finance');
insert into departments (deptID, companyID, deptName) values (570, '764', 'Design');
insert into departments (deptID, companyID, deptName) values (571, '133', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (572, '293', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (573, '111', 'Operations');
insert into departments (deptID, companyID, deptName) values (574, '925', 'Engineering');
insert into departments (deptID, companyID, deptName) values (575, '398', 'Design');
insert into departments (deptID, companyID, deptName) values (576, '678', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (577, '552', 'IT');
insert into departments (deptID, companyID, deptName) values (578, '564', 'Sales');
insert into departments (deptID, companyID, deptName) values (579, '446', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (580, '971', 'IT');
insert into departments (deptID, companyID, deptName) values (581, '105', 'IT');
insert into departments (deptID, companyID, deptName) values (582, '34', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (583, '488', 'Sales');
insert into departments (deptID, companyID, deptName) values (584, '738', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (585, '275', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (586, '657', 'Operations');
insert into departments (deptID, companyID, deptName) values (587, '469', 'Finance');
insert into departments (deptID, companyID, deptName) values (588, '560', 'Design');
insert into departments (deptID, companyID, deptName) values (589, '485', 'Operations');
insert into departments (deptID, companyID, deptName) values (590, '776', 'Finance');
insert into departments (deptID, companyID, deptName) values (591, '82', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (592, '608', 'Marketing');
insert into departments (deptID, companyID, deptName) values (593, '429', 'Design');
insert into departments (deptID, companyID, deptName) values (594, '923', 'Marketing');
insert into departments (deptID, companyID, deptName) values (595, '74', 'Sales');
insert into departments (deptID, companyID, deptName) values (596, '749', 'Design');
insert into departments (deptID, companyID, deptName) values (597, '138', 'Design');
insert into departments (deptID, companyID, deptName) values (598, '32', 'Design');
insert into departments (deptID, companyID, deptName) values (599, '106', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (600, '572', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (601, '906', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (602, '226', 'Engineering');
insert into departments (deptID, companyID, deptName) values (603, '953', 'Marketing');
insert into departments (deptID, companyID, deptName) values (604, '715', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (605, '60', 'Marketing');
insert into departments (deptID, companyID, deptName) values (606, '656', 'Sales');
insert into departments (deptID, companyID, deptName) values (607, '300', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (608, '277', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (609, '708', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (610, '66', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (611, '497', 'Sales');
insert into departments (deptID, companyID, deptName) values (612, '727', 'IT');
insert into departments (deptID, companyID, deptName) values (613, '117', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (614, '360', 'Sales');
insert into departments (deptID, companyID, deptName) values (615, '490', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (616, '797', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (617, '931', 'Design');
insert into departments (deptID, companyID, deptName) values (618, '871', 'IT');
insert into departments (deptID, companyID, deptName) values (619, '970', 'Engineering');
insert into departments (deptID, companyID, deptName) values (620, '139', 'Operations');
insert into departments (deptID, companyID, deptName) values (621, '364', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (622, '897', 'Sales');
insert into departments (deptID, companyID, deptName) values (623, '941', 'Design');
insert into departments (deptID, companyID, deptName) values (624, '240', 'Finance');
insert into departments (deptID, companyID, deptName) values (625, '884', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (626, '866', 'Engineering');
insert into departments (deptID, companyID, deptName) values (627, '351', 'Sales');
insert into departments (deptID, companyID, deptName) values (628, '120', 'Operations');
insert into departments (deptID, companyID, deptName) values (629, '805', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (630, '648', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (631, '917', 'IT');
insert into departments (deptID, companyID, deptName) values (632, '947', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (633, '322', 'Design');
insert into departments (deptID, companyID, deptName) values (634, '395', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (635, '796', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (636, '809', 'Engineering');
insert into departments (deptID, companyID, deptName) values (637, '661', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (638, '175', 'IT');
insert into departments (deptID, companyID, deptName) values (639, '473', 'Sales');
insert into departments (deptID, companyID, deptName) values (640, '865', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (641, '9', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (642, '541', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (643, '288', 'Engineering');
insert into departments (deptID, companyID, deptName) values (644, '205', 'Finance');
insert into departments (deptID, companyID, deptName) values (645, '161', 'Design');
insert into departments (deptID, companyID, deptName) values (646, '69', 'Design');
insert into departments (deptID, companyID, deptName) values (647, '166', 'Engineering');
insert into departments (deptID, companyID, deptName) values (648, '167', 'Marketing');
insert into departments (deptID, companyID, deptName) values (649, '383', 'Marketing');
insert into departments (deptID, companyID, deptName) values (650, '543', 'Operations');
insert into departments (deptID, companyID, deptName) values (651, '354', 'Engineering');
insert into departments (deptID, companyID, deptName) values (652, '402', 'Engineering');
insert into departments (deptID, companyID, deptName) values (653, '744', 'Operations');
insert into departments (deptID, companyID, deptName) values (654, '353', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (655, '347', 'Engineering');
insert into departments (deptID, companyID, deptName) values (656, '507', 'Marketing');
insert into departments (deptID, companyID, deptName) values (657, '315', 'Sales');
insert into departments (deptID, companyID, deptName) values (658, '591', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (659, '695', 'Finance');
insert into departments (deptID, companyID, deptName) values (660, '387', 'Finance');
insert into departments (deptID, companyID, deptName) values (661, '649', 'Marketing');
insert into departments (deptID, companyID, deptName) values (662, '397', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (663, '827', 'Sales');
insert into departments (deptID, companyID, deptName) values (664, '565', 'Operations');
insert into departments (deptID, companyID, deptName) values (665, '382', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (666, '896', 'Operations');
insert into departments (deptID, companyID, deptName) values (667, '162', 'Sales');
insert into departments (deptID, companyID, deptName) values (668, '898', 'Sales');
insert into departments (deptID, companyID, deptName) values (669, '244', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (670, '757', 'Operations');
insert into departments (deptID, companyID, deptName) values (671, '77', 'Engineering');
insert into departments (deptID, companyID, deptName) values (672, '750', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (673, '553', 'Design');
insert into departments (deptID, companyID, deptName) values (674, '477', 'Finance');
insert into departments (deptID, companyID, deptName) values (675, '96', 'Finance');
insert into departments (deptID, companyID, deptName) values (676, '400', 'IT');
insert into departments (deptID, companyID, deptName) values (677, '892', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (678, '278', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (679, '801', 'Engineering');
insert into departments (deptID, companyID, deptName) values (680, '344', 'Design');
insert into departments (deptID, companyID, deptName) values (681, '50', 'Sales');
insert into departments (deptID, companyID, deptName) values (682, '730', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (683, '280', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (684, '577', 'Design');
insert into departments (deptID, companyID, deptName) values (685, '983', 'Operations');
insert into departments (deptID, companyID, deptName) values (686, '363', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (687, '432', 'Sales');
insert into departments (deptID, companyID, deptName) values (688, '889', 'Marketing');
insert into departments (deptID, companyID, deptName) values (689, '963', 'Design');
insert into departments (deptID, companyID, deptName) values (690, '660', 'Finance');
insert into departments (deptID, companyID, deptName) values (691, '873', 'Finance');
insert into departments (deptID, companyID, deptName) values (692, '199', 'IT');
insert into departments (deptID, companyID, deptName) values (693, '405', 'Engineering');
insert into departments (deptID, companyID, deptName) values (694, '311', 'Operations');
insert into departments (deptID, companyID, deptName) values (695, '174', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (696, '419', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (697, '686', 'Engineering');
insert into departments (deptID, companyID, deptName) values (698, '381', 'IT');
insert into departments (deptID, companyID, deptName) values (699, '404', 'Design');
insert into departments (deptID, companyID, deptName) values (700, '483', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (701, '13', 'IT');
insert into departments (deptID, companyID, deptName) values (702, '140', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (703, '724', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (704, '850', 'Finance');
insert into departments (deptID, companyID, deptName) values (705, '424', 'Finance');
insert into departments (deptID, companyID, deptName) values (706, '209', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (707, '46', 'Marketing');
insert into departments (deptID, companyID, deptName) values (708, '599', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (709, '25', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (710, '250', 'Operations');
insert into departments (deptID, companyID, deptName) values (711, '595', 'Marketing');
insert into departments (deptID, companyID, deptName) values (712, '525', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (713, '985', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (714, '95', 'IT');
insert into departments (deptID, companyID, deptName) values (715, '84', 'Finance');
insert into departments (deptID, companyID, deptName) values (716, '75', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (717, '861', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (718, '378', 'Finance');
insert into departments (deptID, companyID, deptName) values (719, '470', 'Design');
insert into departments (deptID, companyID, deptName) values (720, '504', 'Finance');
insert into departments (deptID, companyID, deptName) values (721, '992', 'Engineering');
insert into departments (deptID, companyID, deptName) values (722, '523', 'Operations');
insert into departments (deptID, companyID, deptName) values (723, '930', 'Design');
insert into departments (deptID, companyID, deptName) values (724, '777', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (725, '823', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (726, '887', 'Engineering');
insert into departments (deptID, companyID, deptName) values (727, '818', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (728, '216', 'Sales');
insert into departments (deptID, companyID, deptName) values (729, '233', 'IT');
insert into departments (deptID, companyID, deptName) values (730, '464', 'Marketing');
insert into departments (deptID, companyID, deptName) values (731, '380', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (732, '409', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (733, '664', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (734, '341', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (735, '61', 'Engineering');
insert into departments (deptID, companyID, deptName) values (736, '88', 'Sales');
insert into departments (deptID, companyID, deptName) values (737, '422', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (738, '980', 'Sales');
insert into departments (deptID, companyID, deptName) values (739, '17', 'IT');
insert into departments (deptID, companyID, deptName) values (740, '945', 'Sales');
insert into departments (deptID, companyID, deptName) values (741, '532', 'Design');
insert into departments (deptID, companyID, deptName) values (742, '122', 'Sales');
insert into departments (deptID, companyID, deptName) values (743, '622', 'IT');
insert into departments (deptID, companyID, deptName) values (744, '555', 'Finance');
insert into departments (deptID, companyID, deptName) values (745, '373', 'Sales');
insert into departments (deptID, companyID, deptName) values (746, '719', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (747, '262', 'Engineering');
insert into departments (deptID, companyID, deptName) values (748, '242', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (749, '762', 'IT');
insert into departments (deptID, companyID, deptName) values (750, '178', 'Engineering');
insert into departments (deptID, companyID, deptName) values (751, '476', 'Engineering');
insert into departments (deptID, companyID, deptName) values (752, '987', 'Design');
insert into departments (deptID, companyID, deptName) values (753, '153', 'Engineering');
insert into departments (deptID, companyID, deptName) values (754, '668', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (755, '674', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (756, '807', 'Engineering');
insert into departments (deptID, companyID, deptName) values (757, '721', 'Marketing');
insert into departments (deptID, companyID, deptName) values (758, '218', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (759, '597', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (760, '842', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (761, '62', 'Operations');
insert into departments (deptID, companyID, deptName) values (762, '388', 'Finance');
insert into departments (deptID, companyID, deptName) values (763, '411', 'Finance');
insert into departments (deptID, companyID, deptName) values (764, '748', 'Marketing');
insert into departments (deptID, companyID, deptName) values (765, '403', 'Operations');
insert into departments (deptID, companyID, deptName) values (766, '607', 'Finance');
insert into departments (deptID, companyID, deptName) values (767, '836', 'Finance');
insert into departments (deptID, companyID, deptName) values (768, '939', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (769, '500', 'Marketing');
insert into departments (deptID, companyID, deptName) values (770, '85', 'IT');
insert into departments (deptID, companyID, deptName) values (771, '19', 'Operations');
insert into departments (deptID, companyID, deptName) values (772, '645', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (773, '996', 'Operations');
insert into departments (deptID, companyID, deptName) values (774, '839', 'Finance');
insert into departments (deptID, companyID, deptName) values (775, '913', 'Sales');
insert into departments (deptID, companyID, deptName) values (776, '637', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (777, '821', 'IT');
insert into departments (deptID, companyID, deptName) values (778, '306', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (779, '763', 'Marketing');
insert into departments (deptID, companyID, deptName) values (780, '350', 'Marketing');
insert into departments (deptID, companyID, deptName) values (781, '672', 'Marketing');
insert into departments (deptID, companyID, deptName) values (782, '617', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (783, '559', 'Finance');
insert into departments (deptID, companyID, deptName) values (784, '707', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (785, '568', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (786, '380', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (787, '346', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (788, '638', 'Finance');
insert into departments (deptID, companyID, deptName) values (789, '66', 'Marketing');
insert into departments (deptID, companyID, deptName) values (790, '519', 'Sales');
insert into departments (deptID, companyID, deptName) values (791, '371', 'Design');
insert into departments (deptID, companyID, deptName) values (792, '125', 'Operations');
insert into departments (deptID, companyID, deptName) values (793, '369', 'Design');
insert into departments (deptID, companyID, deptName) values (794, '506', 'Design');
insert into departments (deptID, companyID, deptName) values (795, '675', 'Marketing');
insert into departments (deptID, companyID, deptName) values (796, '613', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (797, '373', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (798, '918', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (799, '242', 'Finance');
insert into departments (deptID, companyID, deptName) values (800, '643', 'Finance');
insert into departments (deptID, companyID, deptName) values (801, '697', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (802, '494', 'IT');
insert into departments (deptID, companyID, deptName) values (803, '473', 'Marketing');
insert into departments (deptID, companyID, deptName) values (804, '626', 'Finance');
insert into departments (deptID, companyID, deptName) values (805, '647', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (806, '454', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (807, '512', 'Marketing');
insert into departments (deptID, companyID, deptName) values (808, '1', 'Engineering');
insert into departments (deptID, companyID, deptName) values (809, '6', 'Marketing');
insert into departments (deptID, companyID, deptName) values (810, '196', 'Finance');
insert into departments (deptID, companyID, deptName) values (811, '780', 'Engineering');
insert into departments (deptID, companyID, deptName) values (812, '983', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (813, '497', 'Finance');
insert into departments (deptID, companyID, deptName) values (814, '450', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (815, '684', 'Finance');
insert into departments (deptID, companyID, deptName) values (816, '439', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (817, '402', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (818, '975', 'Marketing');
insert into departments (deptID, companyID, deptName) values (819, '87', 'Finance');
insert into departments (deptID, companyID, deptName) values (820, '159', 'Marketing');
insert into departments (deptID, companyID, deptName) values (821, '479', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (822, '35', 'Engineering');
insert into departments (deptID, companyID, deptName) values (823, '706', 'Design');
insert into departments (deptID, companyID, deptName) values (824, '969', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (825, '895', 'Finance');
insert into departments (deptID, companyID, deptName) values (826, '283', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (827, '116', 'Design');
insert into departments (deptID, companyID, deptName) values (828, '59', 'Marketing');
insert into departments (deptID, companyID, deptName) values (829, '424', 'Finance');
insert into departments (deptID, companyID, deptName) values (830, '376', 'Sales');
insert into departments (deptID, companyID, deptName) values (831, '181', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (832, '771', 'Design');
insert into departments (deptID, companyID, deptName) values (833, '157', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (834, '529', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (835, '397', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (836, '870', 'Finance');
insert into departments (deptID, companyID, deptName) values (837, '114', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (838, '436', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (839, '632', 'Engineering');
insert into departments (deptID, companyID, deptName) values (840, '597', 'Operations');
insert into departments (deptID, companyID, deptName) values (841, '298', 'Engineering');
insert into departments (deptID, companyID, deptName) values (842, '429', 'Design');
insert into departments (deptID, companyID, deptName) values (843, '504', 'Sales');
insert into departments (deptID, companyID, deptName) values (844, '260', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (845, '640', 'Engineering');
insert into departments (deptID, companyID, deptName) values (846, '547', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (847, '901', 'Sales');
insert into departments (deptID, companyID, deptName) values (848, '108', 'Marketing');
insert into departments (deptID, companyID, deptName) values (849, '398', 'Finance');
insert into departments (deptID, companyID, deptName) values (850, '944', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (851, '941', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (852, '173', 'Design');
insert into departments (deptID, companyID, deptName) values (853, '981', 'Engineering');
insert into departments (deptID, companyID, deptName) values (854, '384', 'IT');
insert into departments (deptID, companyID, deptName) values (855, '542', 'Operations');
insert into departments (deptID, companyID, deptName) values (856, '839', 'Design');
insert into departments (deptID, companyID, deptName) values (857, '723', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (858, '156', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (859, '906', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (860, '865', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (861, '935', 'Design');
insert into departments (deptID, companyID, deptName) values (862, '190', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (863, '922', 'Sales');
insert into departments (deptID, companyID, deptName) values (864, '255', 'IT');
insert into departments (deptID, companyID, deptName) values (865, '161', 'IT');
insert into departments (deptID, companyID, deptName) values (866, '850', 'IT');
insert into departments (deptID, companyID, deptName) values (867, '814', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (868, '105', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (869, '8', 'Engineering');
insert into departments (deptID, companyID, deptName) values (870, '395', 'Engineering');
insert into departments (deptID, companyID, deptName) values (871, '999', 'Sales');
insert into departments (deptID, companyID, deptName) values (872, '275', 'Operations');
insert into departments (deptID, companyID, deptName) values (873, '431', 'Engineering');
insert into departments (deptID, companyID, deptName) values (874, '261', 'Design');
insert into departments (deptID, companyID, deptName) values (875, '700', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (876, '449', 'Operations');
insert into departments (deptID, companyID, deptName) values (877, '316', 'Sales');
insert into departments (deptID, companyID, deptName) values (878, '790', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (879, '811', 'Engineering');
insert into departments (deptID, companyID, deptName) values (880, '302', 'Finance');
insert into departments (deptID, companyID, deptName) values (881, '19', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (882, '791', 'Design');
insert into departments (deptID, companyID, deptName) values (883, '309', 'Sales');
insert into departments (deptID, companyID, deptName) values (884, '745', 'Sales');
insert into departments (deptID, companyID, deptName) values (885, '222', 'Sales');
insert into departments (deptID, companyID, deptName) values (886, '227', 'Finance');
insert into departments (deptID, companyID, deptName) values (887, '832', 'Design');
insert into departments (deptID, companyID, deptName) values (888, '550', 'Marketing');
insert into departments (deptID, companyID, deptName) values (889, '779', 'Engineering');
insert into departments (deptID, companyID, deptName) values (890, '293', 'Engineering');
insert into departments (deptID, companyID, deptName) values (891, '197', 'Marketing');
insert into departments (deptID, companyID, deptName) values (892, '308', 'IT');
insert into departments (deptID, companyID, deptName) values (893, '55', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (894, '477', 'IT');
insert into departments (deptID, companyID, deptName) values (895, '45', 'Engineering');
insert into departments (deptID, companyID, deptName) values (896, '10', 'Marketing');
insert into departments (deptID, companyID, deptName) values (897, '287', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (898, '162', 'Engineering');
insert into departments (deptID, companyID, deptName) values (899, '663', 'IT');
insert into departments (deptID, companyID, deptName) values (900, '946', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (901, '579', 'IT');
insert into departments (deptID, companyID, deptName) values (902, '743', 'Design');
insert into departments (deptID, companyID, deptName) values (903, '898', 'Operations');
insert into departments (deptID, companyID, deptName) values (904, '651', 'Sales');
insert into departments (deptID, companyID, deptName) values (905, '117', 'Finance');
insert into departments (deptID, companyID, deptName) values (906, '631', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (907, '199', 'Design');
insert into departments (deptID, companyID, deptName) values (908, '294', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (909, '557', 'Operations');
insert into departments (deptID, companyID, deptName) values (910, '273', 'Sales');
insert into departments (deptID, companyID, deptName) values (911, '893', 'Design');
insert into departments (deptID, companyID, deptName) values (912, '905', 'IT');
insert into departments (deptID, companyID, deptName) values (913, '502', 'Operations');
insert into departments (deptID, companyID, deptName) values (914, '873', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (915, '332', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (916, '254', 'Sales');
insert into departments (deptID, companyID, deptName) values (917, '404', 'Marketing');
insert into departments (deptID, companyID, deptName) values (918, '182', 'IT');
insert into departments (deptID, companyID, deptName) values (919, '374', 'Engineering');
insert into departments (deptID, companyID, deptName) values (920, '989', 'Marketing');
insert into departments (deptID, companyID, deptName) values (921, '328', 'Engineering');
insert into departments (deptID, companyID, deptName) values (922, '938', 'Finance');
insert into departments (deptID, companyID, deptName) values (923, '531', 'Marketing');
insert into departments (deptID, companyID, deptName) values (924, '654', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (925, '528', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (926, '883', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (927, '362', 'Sales');
insert into departments (deptID, companyID, deptName) values (928, '148', 'Sales');
insert into departments (deptID, companyID, deptName) values (929, '103', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (930, '245', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (931, '837', 'IT');
insert into departments (deptID, companyID, deptName) values (932, '951', 'Operations');
insert into departments (deptID, companyID, deptName) values (933, '310', 'Operations');
insert into departments (deptID, companyID, deptName) values (934, '210', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (935, '272', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (936, '237', 'Operations');
insert into departments (deptID, companyID, deptName) values (937, '124', 'Engineering');
insert into departments (deptID, companyID, deptName) values (938, '871', 'Finance');
insert into departments (deptID, companyID, deptName) values (939, '368', 'Design');
insert into departments (deptID, companyID, deptName) values (940, '823', 'Design');
insert into departments (deptID, companyID, deptName) values (941, '97', 'Operations');
insert into departments (deptID, companyID, deptName) values (942, '27', 'Finance');
insert into departments (deptID, companyID, deptName) values (943, '829', 'Sales');
insert into departments (deptID, companyID, deptName) values (944, '827', 'Operations');
insert into departments (deptID, companyID, deptName) values (945, '339', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (946, '584', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (947, '214', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (948, '853', 'Finance');
insert into departments (deptID, companyID, deptName) values (949, '698', 'Operations');
insert into departments (deptID, companyID, deptName) values (950, '876', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (951, '208', 'Finance');
insert into departments (deptID, companyID, deptName) values (952, '420', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (953, '168', 'IT');
insert into departments (deptID, companyID, deptName) values (954, '758', 'Design');
insert into departments (deptID, companyID, deptName) values (955, '423', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (956, '520', 'Marketing');
insert into departments (deptID, companyID, deptName) values (957, '599', 'IT');
insert into departments (deptID, companyID, deptName) values (958, '426', 'IT');
insert into departments (deptID, companyID, deptName) values (959, '432', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (960, '463', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (961, '607', 'Sales');
insert into departments (deptID, companyID, deptName) values (962, '11', 'Operations');
insert into departments (deptID, companyID, deptName) values (963, '150', 'Sales');
insert into departments (deptID, companyID, deptName) values (964, '563', 'Sales');
insert into departments (deptID, companyID, deptName) values (965, '232', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (966, '211', 'Design');
insert into departments (deptID, companyID, deptName) values (967, '476', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (968, '707', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (969, '498', 'IT');
insert into departments (deptID, companyID, deptName) values (970, '347', 'Marketing');
insert into departments (deptID, companyID, deptName) values (971, '102', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (972, '361', 'Sales');
insert into departments (deptID, companyID, deptName) values (973, '819', 'IT');
insert into departments (deptID, companyID, deptName) values (974, '573', 'Marketing');
insert into departments (deptID, companyID, deptName) values (975, '315', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (976, '71', 'Engineering');
insert into departments (deptID, companyID, deptName) values (977, '5', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (978, '101', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (979, '149', 'Operations');
insert into departments (deptID, companyID, deptName) values (980, '443', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (981, '993', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (982, '545', 'Design');
insert into departments (deptID, companyID, deptName) values (983, '296', 'Design');
insert into departments (deptID, companyID, deptName) values (984, '661', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (985, '505', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (986, '113', 'Human Resources');
insert into departments (deptID, companyID, deptName) values (987, '674', 'IT');
insert into departments (deptID, companyID, deptName) values (988, '820', 'Design');
insert into departments (deptID, companyID, deptName) values (989, '213', 'Design');
insert into departments (deptID, companyID, deptName) values (990, '451', 'Marketing');
insert into departments (deptID, companyID, deptName) values (991, '798', 'Public Relations');
insert into departments (deptID, companyID, deptName) values (992, '776', 'Design');
insert into departments (deptID, companyID, deptName) values (993, '349', 'Finance');
insert into departments (deptID, companyID, deptName) values (994, '65', 'Marketing');
insert into departments (deptID, companyID, deptName) values (995, '73', 'Sales');
insert into departments (deptID, companyID, deptName) values (996, '924', 'Operations');
insert into departments (deptID, companyID, deptName) values (997, '3', 'Research and Development');
insert into departments (deptID, companyID, deptName) values (998, '848', 'IT');
insert into departments (deptID, companyID, deptName) values (999, '686', 'Marketing');
insert into departments (deptID, companyID, deptName) values (1000, '445', 'Finance');
